spring.application.name=Chapter12-03
custom.datasource.url=jdbc:mysql://localhost:3306/Spring?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
custom.datasource.username=root
custom.datasource.password=password
spring.sql.init.mode=always