spring.application.name=Chapter12-02
spring.datasource.url=jdbc:mysql://localhost:3306/Spring?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password
spring.sql.init.mode=always